// Keep this contract aligned with the fraction catalog and renderer.
module.exports = `Fraction figures use { "type": "fraction", "params": { ... }, "caption": "<neutral description>" }.
Use showLabel:false for questions. Never reveal the answer in captions, panel labels, or alt text.
Supported params (all indices are zero-based):
- Equal pie/bar: {style:"pie"|"bar", numerator:0..1200, denominator:1..100, showLabel:false}. Numerator may exceed denominator; at most 12 congruent wholes. Zero is valid. Optional shadedIndices selects non-consecutive parts of ONE whole; its length must equal numerator.
- Triangles split into three equal areas: {style:"triangle", numerator:4, denominator:3, showLabel:false} shows one whole and one third.
- Grid with whole and half shaded cells: {style:"grid", rows:2, cols:3, cells:["full","empty","top-left","bottom-right","top-right","bottom-left"], showLabel:false}. Exactly rows*cols cells, row-major, at most 100. Each corner name shades that triangular HALF of a cell; empty/full have area 0/1. Calculate shaded area as full cells + half cells/2, divided by rows*cols. Do not count unequal pieces as equal units.
- Composite shapes or triangular tessellations: {style:"regions", regions:[{points:[[0,0],[50,0],[0,50]],shaded:true},{points:[[50,0],[50,50],[0,50]],shaded:false}], showLabel:false}. Coordinates in 0..100; 3..12 vertices per polygon, 1..100 non-overlapping convex polygons, no self-intersections. Regions together define the whole. Derive the fraction from polygon AREAS, not number of pieces. Use simple exact geometry. Do not invent equal-area claims.
- Unequal pie sectors: {style:"pie", sectorWeights:[2,1,1,2,1,1], numerator:3, denominator:6, shadedIndices:[0,2,4], showLabel:false}. Sector weights are positive relative angles. Area fraction is SUM OF SHADED WEIGHTS / SUM OF ALL WEIGHTS. numerator counts shaded sectors, not area units.
- Concentric regions: add rings:[{innerRadius:0,outerRadius:0.4,shadedIndices:[1,3]},{innerRadius:0.4,outerRadius:1,shadedIndices:[0,2]}] to a pie with sectorWeights. Rings must tile radius 0..1 without gaps/overlaps. Compute each shaded area using (outerRadius^2-innerRadius^2)*shadedWeight/totalWeight.
- Object collections: {style:"set", items:[{shape:"circle"|"square"|"triangle"|"star",shaded:true|false},...], cols:4, outline:true, showLabel:false}. At most 100 items. Count requested shape or shaded objects / total items. For identical beads use {style:"set",numerator:4,denominator:7,layout:"necklace",shadedIndices:[0,2,4,6],showLabel:false}. Optional itemShape selects an identical object shape.
- Multiple figures: {panels:[{label:"X",style:"grid",rows:2,cols:2,cells:["top-left","bottom-right","top-left","bottom-right"]},{label:"A",style:"pie",numerator:2,denominator:4},{label:"B",style:"triangle",numerator:2,denominator:3},{label:"C",text:"None of these"}],showLabel:false}. 1..12 flat panels. Each panel uses a supported shape format or text. Use labels A/B/C/D matching normal question.options text for figure choices; keep diagrams in this top-level panel collection (not inside options). Use X for a reference figure and P/Q or (i)/(ii)/(iii) for comparisons or counting. Do not nest panels.
Generate varied figure-to-fraction, unshaded/complement, fraction-to-figure, equivalent/comparison, mixed-number, half-cell area, shape-counting, necklace, figure arithmetic, and count-the-correct-figures questions when the chosen exercise format calls for them. For arithmetic label the figures P and Q and put the operation in question text. Explicitly say whether one shape is one whole or the collection is one whole. For mcq-single verify exactly one answer is correct, including equivalence of distractor fractions. For unshaded questions retain actual shaded geometry and compute its complement; do not invert the diagram to display the answer.`;
